name: Deploy to Namecheap

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Clean server (keep .htaccess and maintainPage)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.NAMESCHEAP_HOST }}
          username: ${{ secrets.NAMESCHEAP_USERNAME }}
          key: ${{ secrets.NAMESCHEAP_SSH_KEY }}
          port: ${{ secrets.NAMESCHEAP_PORT }}
          script: |
            set -e
            cd /home/${{ secrets.NAMESCHEAP_USERNAME }}/public_html
            echo "Cleaning deployment directory..."
            find . -mindepth 1 \
              ! -name ".htaccess" \
              ! -name "maintainPage" \
              -exec rm -rf {} +

            echo "Cleanup completed."

      - name: Upload dist files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.NAMESCHEAP_HOST }}
          username: ${{ secrets.NAMESCHEAP_USERNAME }}
          key: ${{ secrets.NAMESCHEAP_SSH_KEY }}
          port: ${{ secrets.NAMESCHEAP_PORT }}
          source: "dist/*"
          target: "/home/${{ secrets.NAMESCHEAP_USERNAME }}/public_html"
          # strip_components: 1

      # - name: Verify deployment
      #   uses: appleboy/ssh-action@v1.2.0
      #   with:
      #     host: ${{ secrets.NAMESCHEAP_HOST }}
      #     username: ${{ secrets.NAMESCHEAP_USERNAME }}
      #     key: ${{ secrets.NAMESCHEAP_SSH_KEY }}
      #     port: ${{ secrets.NAMESCHEAP_PORT }}
      #     script: |
      #       cd /home/${{ secrets.NAMESCHEAP_USERNAME }}/public_html

      #       echo "Deployment completed."
      #       ls -la